//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.MM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.DeviceManagerMachineModules.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 老化模式 的本地化字符串。
        /// </summary>
        public static string AgingMode {
            get {
                return ResourceManager.GetString("AgingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置模式 的本地化字符串。
        /// </summary>
        public static string ConfigMode {
            get {
                return ResourceManager.GetString("ConfigMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续执行 的本地化字符串。
        /// </summary>
        public static string Continuous {
            get {
                return ResourceManager.GetString("Continuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前配方名称 的本地化字符串。
        /// </summary>
        public static string CurFormulaNumber {
            get {
                return ResourceManager.GetString("CurFormulaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设计时 的本地化字符串。
        /// </summary>
        public static string DesignTime {
            get {
                return ResourceManager.GetString("DesignTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制流程执行模式 的本地化字符串。
        /// </summary>
        public static string ExecMode {
            get {
                return ResourceManager.GetString("ExecMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配方名称列表 的本地化字符串。
        /// </summary>
        public static string FormulaNumberList {
            get {
                return ResourceManager.GetString("FormulaNumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行模式 的本地化字符串。
        /// </summary>
        public static string ImeRunMode {
            get {
                return ResourceManager.GetString("ImeRunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行模式列表 的本地化字符串。
        /// </summary>
        public static string RunModeList {
            get {
                return ResourceManager.GetString("RunModeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单工艺流程周期执行 的本地化字符串。
        /// </summary>
        public static string SingleCycle {
            get {
                return ResourceManager.GetString("SingleCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单步执行 的本地化字符串。
        /// </summary>
        public static string SingleStep {
            get {
                return ResourceManager.GetString("SingleStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作模式 的本地化字符串。
        /// </summary>
        public static string WorkMode {
            get {
                return ResourceManager.GetString("WorkMode", resourceCulture);
            }
        }
    }
}
