//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.ElectronicControl {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MotionErr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MotionErr() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.ElectronicControl.MotionControlCard.MotionErr", typeof(MotionErr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动设置最大速度失败 的本地化字符串。
        /// </summary>
        public static string AbsoluteMoveMaxSpeed {
            get {
                return ResourceManager.GetString("AbsoluteMoveMaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动启动运动失败 的本地化字符串。
        /// </summary>
        public static string AbsoluteMoveStart {
            get {
                return ResourceManager.GetString("AbsoluteMoveStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动设置起跳速度失败 的本地化字符串。
        /// </summary>
        public static string AbsoluteMoveStartSpeed {
            get {
                return ResourceManager.GetString("AbsoluteMoveStartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动设置目标位置失败 的本地化字符串。
        /// </summary>
        public static string AbsoluteMoveTargetPosition {
            get {
                return ResourceManager.GetString("AbsoluteMoveTargetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绝对运动失败 的本地化字符串。
        /// </summary>
        public static string AbsuloteMoveFail {
            get {
                return ResourceManager.GetString("AbsuloteMoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴绑定信息不包含指定轴 的本地化字符串。
        /// </summary>
        public static string AxisBindingPairsNotExist {
            get {
                return ResourceManager.GetString("AxisBindingPairsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴绑定信息为空 的本地化字符串。
        /// </summary>
        public static string AxisBindingPairsNull {
            get {
                return ResourceManager.GetString("AxisBindingPairsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴数量错误 的本地化字符串。
        /// </summary>
        public static string AxisCountErr {
            get {
                return ResourceManager.GetString("AxisCountErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴回零失败 的本地化字符串。
        /// </summary>
        public static string AxisHomeFail {
            get {
                return ResourceManager.GetString("AxisHomeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴锁定字典不包含指定轴 的本地化字符串。
        /// </summary>
        public static string AxisLockGuidNotExist {
            get {
                return ResourceManager.GetString("AxisLockGuidNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴锁定字典为空 的本地化字符串。
        /// </summary>
        public static string AxisLockGuidNull {
            get {
                return ResourceManager.GetString("AxisLockGuidNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴号超出范围 的本地化字符串。
        /// </summary>
        public static string AxisOutOfRange {
            get {
                return ResourceManager.GetString("AxisOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插补运动失败 的本地化字符串。
        /// </summary>
        public static string InterpolationFail {
            get {
                return ResourceManager.GetString("InterpolationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运控卡初始化失败 的本地化字符串。
        /// </summary>
        public static string MotionCardInitFailed {
            get {
                return ResourceManager.GetString("MotionCardInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线变速失败 的本地化字符串。
        /// </summary>
        public static string OnlineSpeedChangeFail {
            get {
                return ResourceManager.GetString("OnlineSpeedChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线变位失败 的本地化字符串。
        /// </summary>
        public static string OnlineTargetPositionChangeFail {
            get {
                return ResourceManager.GetString("OnlineTargetPositionChangeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防呆检查未通过 的本地化字符串。
        /// </summary>
        public static string PokaYokeCheckFailed {
            get {
                return ResourceManager.GetString("PokaYokeCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相对运动失败 的本地化字符串。
        /// </summary>
        public static string RelativeMoveFail {
            get {
                return ResourceManager.GetString("RelativeMoveFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机械手运动错误 的本地化字符串。
        /// </summary>
        public static string RobotMoveFailed {
            get {
                return ResourceManager.GetString("RobotMoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机械手运动超时 的本地化字符串。
        /// </summary>
        public static string RobotMoveTimeout {
            get {
                return ResourceManager.GetString("RobotMoveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置软限位失败 的本地化字符串。
        /// </summary>
        public static string SetSoftLimitFail {
            get {
                return ResourceManager.GetString("SetSoftLimitFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续运动失败 的本地化字符串。
        /// </summary>
        public static string VelocityMoveFail {
            get {
                return ResourceManager.GetString("VelocityMoveFail", resourceCulture);
            }
        }
    }
}
