//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.SubMM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.EletronicManagerSubMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AfterStopWork 尚未实现。 的本地化字符串。
        /// </summary>
        public static string AfterStopWorkNotImplemented {
            get {
                return ResourceManager.GetString("AfterStopWorkNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未加载轴配置信息，无法构建RobotDriver。 的本地化字符串。
        /// </summary>
        public static string AxisConfigNotLoaded {
            get {
                return ResourceManager.GetString("AxisConfigNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求的轴ID列表跨越了多张运控卡，当前仅支持同一张卡创建RobotDriver。 的本地化字符串。
        /// </summary>
        public static string AxisIdsAcrossMultipleMotionCards {
            get {
                return ResourceManager.GetString("AxisIdsAcrossMultipleMotionCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到对应轴ID的轴信息: {0} 的本地化字符串。
        /// </summary>
        public static string AxisInfoNotFoundById {
            get {
                return ResourceManager.GetString("AxisInfoNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BeforeSwitchPF 尚未实现。 的本地化字符串。
        /// </summary>
        public static string BeforeSwitchPFNotImplemented {
            get {
                return ResourceManager.GetString("BeforeSwitchPFNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EletronicFactoryParameters为空，无法初始化运控卡 的本地化字符串。
        /// </summary>
        public static string FactoryParametersNull {
            get {
                return ResourceManager.GetString("FactoryParametersNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO状态量未配置ChannelId: {0} 的本地化字符串。
        /// </summary>
        public static string IoStateChannelIdNotConfigured {
            get {
                return ResourceManager.GetString("IoStateChannelIdNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未加载IO状态量配置信息，无法获取状态量实例。 的本地化字符串。
        /// </summary>
        public static string IoStateConfigNotLoaded {
            get {
                return ResourceManager.GetString("IoStateConfigNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO状态量未配置DeviceGuid: {0} 的本地化字符串。
        /// </summary>
        public static string IoStateDeviceGuidNotConfigured {
            get {
                return ResourceManager.GetString("IoStateDeviceGuidNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到对应IOGuid的IO状态量信息: {0} 的本地化字符串。
        /// </summary>
        public static string IoStateInfoNotFoundByGuid {
            get {
                return ResourceManager.GetString("IoStateInfoNotFoundByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运控卡配置MotionCardID重复:{0} 的本地化字符串。
        /// </summary>
        public static string MotionCardIdDuplicate {
            get {
                return ResourceManager.GetString("MotionCardIdDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运控卡配置MotionCardID为空，类型:{0} 的本地化字符串。
        /// </summary>
        public static string MotionCardIdEmpty {
            get {
                return ResourceManager.GetString("MotionCardIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运控卡初始化失败，类型:{0}，ID:{1}，返回码:{2} 的本地化字符串。
        /// </summary>
        public static string MotionCardInitFailed {
            get {
                return ResourceManager.GetString("MotionCardInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到所属运控卡实例: {0} 的本地化字符串。
        /// </summary>
        public static string MotionCardInstanceNotFoundByCardGuid {
            get {
                return ResourceManager.GetString("MotionCardInstanceNotFoundByCardGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到IO所属运控卡状态量实例表: {0} 的本地化字符串。
        /// </summary>
        public static string MotionCardStateIoTableNotFound {
            get {
                return ResourceManager.GetString("MotionCardStateIoTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MotionControlCardInformations为空，未配置任何运控卡 的本地化字符串。
        /// </summary>
        public static string MotionControlCardInformationsEmpty {
            get {
                return ResourceManager.GetString("MotionControlCardInformationsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到对应IO状态量实例，CardGuid:{0}, ChannelId:{1} 的本地化字符串。
        /// </summary>
        public static string StateIoInstanceNotFound {
            get {
                return ResourceManager.GetString("StateIoInstanceNotFound", resourceCulture);
            }
        }
    }
}
