//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.AuxiliaryFunctionsFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.AuxiliaryFunctionsFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助功能.
        /// </summary>
        internal static string AuxiliaryFunctions {
            get {
                return ResourceManager.GetString("AuxiliaryFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色操作原子.
        /// </summary>
        internal static string BackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色操作.
        /// </summary>
        internal static string BackColor_MapOprtName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 气压值.
        /// </summary>
        internal static string PressureValue {
            get {
                return ResourceManager.GetString("PressureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 气压值操作原子.
        /// </summary>
        internal static string PressureValue_MapOprtCellName {
            get {
                return ResourceManager.GetString("PressureValue_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 气压值操作.
        /// </summary>
        internal static string PressureValue_MapOprtName {
            get {
                return ResourceManager.GetString("PressureValue_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式1.
        /// </summary>
        internal static string Style1 {
            get {
                return ResourceManager.GetString("Style1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式2.
        /// </summary>
        internal static string Style2 {
            get {
                return ResourceManager.GetString("Style2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本颜色操作原子.
        /// </summary>
        internal static string TextColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本颜色操作.
        /// </summary>
        internal static string TextColor_MapOprtName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体.
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体操作原子.
        /// </summary>
        internal static string TextFont_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体操作.
        /// </summary>
        internal static string TextFont_MapOprtName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtName", resourceCulture);
            }
        }
    }
}
