//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.LoadUnloadMachineModules.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.LoadUnloadMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空料 的本地化字符串。
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满料 的本地化字符串。
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化失败 的本地化字符串。
        /// </summary>
        public static string InitFailed {
            get {
                return ResourceManager.GetString("InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法识别 StorageBoxName：{0} 的本地化字符串。
        /// </summary>
        public static string InvalidStorageBoxNameFormat {
            get {
                return ResourceManager.GetString("InvalidStorageBoxNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法识别 StorageDeviceName/StorageBoxName：StorageDeviceName={0}, StorageBoxName={1} 的本地化字符串。
        /// </summary>
        public static string InvalidStorageDeviceOrBoxNameFormat {
            get {
                return ResourceManager.GetString("InvalidStorageDeviceOrBoxNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为空 的本地化字符串。
        /// </summary>
        public static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否属于上料类型 的本地化字符串。
        /// </summary>
        public static string IsFeeding {
            get {
                return ResourceManager.GetString("IsFeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总控未初始化，无法转发到料盒子模组。 的本地化字符串。
        /// </summary>
        public static string LoadUnloadNotInitializedForMaterialBoxForwarding {
            get {
                return ResourceManager.GetString("LoadUnloadNotInitializedForMaterialBoxForwarding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒气缸状态 的本地化字符串。
        /// </summary>
        public static string MaterialBoxCylinderStatus {
            get {
                return ResourceManager.GetString("MaterialBoxCylinderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒子模组未返回结果。 的本地化字符串。
        /// </summary>
        public static string MaterialBoxSubModuleReturnedNullResult {
            get {
                return ResourceManager.GetString("MaterialBoxSubModuleReturnedNullResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器列表 的本地化字符串。
        /// </summary>
        public static string MaterialContainers {
            get {
                return ResourceManager.GetString("MaterialContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料槽状态 的本地化字符串。
        /// </summary>
        public static string MaterialStatus {
            get {
                return ResourceManager.GetString("MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料槽状态列表 的本地化字符串。
        /// </summary>
        public static string SlotStatusList {
            get {
                return ResourceManager.GetString("SlotStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面数据对象未注入运行时命令执行器。 的本地化字符串。
        /// </summary>
        public static string UIDataObjRuntimeCommandExecutorNotInjected {
            get {
                return ResourceManager.GetString("UIDataObjRuntimeCommandExecutorNotInjected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未识别的运行时命令: {0} 的本地化字符串。
        /// </summary>
        public static string UnrecognizedRuntimeCommandFormat {
            get {
                return ResourceManager.GetString("UnrecognizedRuntimeCommandFormat", resourceCulture);
            }
        }
    }
}
