//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.HeatingControl {
    using System;

    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.HeatingControl.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对使用此强类型资源类的所有资源查找执行重写
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 加热控制 的本地化字符串
        /// </summary>
        internal static string HeatingControl {
            get {
                return ResourceManager.GetString("HeatingControl", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 双阀模式 的本地化字符串
        /// </summary>
        internal static string IsDualValve {
            get {
                return ResourceManager.GetString("IsDualValve", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 双轨模式 的本地化字符串
        /// </summary>
        internal static string IsDualTrack {
            get {
                return ResourceManager.GetString("IsDualTrack", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-关/开 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_Switch {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-当前温度 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_CurrentTemperature {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-设定温度 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_SetTemperature {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-温度范围 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_TemperatureRange {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_IdleCloseInterval {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-预热时间 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_PreheatTime {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-加热时间 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_HeatingTime {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-检测开启 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_DetectionEnabled {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-工作开启 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_WorkEnabled {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀点胶头-延迟时间 的本地化字符串
        /// </summary>
        internal static string RightValveDispensingHead_DelayTime {
            get {
                return ResourceManager.GetString("RightValveDispensingHead_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-关/开 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_Switch {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-当前温度 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_CurrentTemperature {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-设定温度 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_SetTemperature {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-温度范围 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_TemperatureRange {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_IdleCloseInterval {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-预热时间 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_PreheatTime {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-加热时间 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_HeatingTime {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-检测开启 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_DetectionEnabled {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-工作开启 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_WorkEnabled {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶筒加热-延迟时间 的本地化字符串
        /// </summary>
        internal static string RightValveCartridgeHeating_DelayTime {
            get {
                return ResourceManager.GetString("RightValveCartridgeHeating_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-关/开 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_Switch {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-当前温度 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_CurrentTemperature {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-设定温度 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_SetTemperature {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-温度范围 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_TemperatureRange {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_IdleCloseInterval {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-预热时间 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_PreheatTime {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-加热时间 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_HeatingTime {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-检测开启 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_DetectionEnabled {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-工作开启 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_WorkEnabled {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀点胶头-延迟时间 的本地化字符串
        /// </summary>
        internal static string LeftValveDispensingHead_DelayTime {
            get {
                return ResourceManager.GetString("LeftValveDispensingHead_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-关/开 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_Switch {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-当前温度 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_CurrentTemperature {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-设定温度 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_SetTemperature {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-温度范围 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_TemperatureRange {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_IdleCloseInterval {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-预热时间 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_PreheatTime {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-加热时间 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_HeatingTime {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-检测开启 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_DetectionEnabled {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-工作开启 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_WorkEnabled {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶筒加热-延迟时间 的本地化字符串
        /// </summary>
        internal static string LeftValveCartridgeHeating_DelayTime {
            get {
                return ResourceManager.GetString("LeftValveCartridgeHeating_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-关/开 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_Switch {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_SetTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_PreheatTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_HeatingTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft_DelayTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-关/开 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_Switch {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_SetTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_PreheatTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_HeatingTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-左(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatLeft2_DelayTime {
            get {
                return ResourceManager.GetString("ARailPreheatLeft2_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-关/开 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_Switch {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_SetTemperature {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_PreheatTime {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_HeatingTime {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨胶板工位-中-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailGlueBoardStationMiddle_DelayTime {
            get {
                return ResourceManager.GetString("ARailGlueBoardStationMiddle_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-关/开 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_Switch {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_SetTemperature {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_PreheatTime {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_HeatingTime {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨点胶工位-中(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailDispensingStationMiddle2_DelayTime {
            get {
                return ResourceManager.GetString("ARailDispensingStationMiddle2_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-关/开 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_Switch {
            get {
                return ResourceManager.GetString("ARailPreheatRight_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatRight_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_SetTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatRight_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailPreheatRight_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailPreheatRight_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_PreheatTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_HeatingTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatRight_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatRight_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight_DelayTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-关/开 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_Switch {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_CurrentTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_SetTemperature {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_TemperatureRange {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_PreheatTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_HeatingTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_DetectionEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_WorkEnabled {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A轨预热-右(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string ARailPreheatRight2_DelayTime {
            get {
                return ResourceManager.GetString("ARailPreheatRight2_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-关/开 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_Switch {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_SetTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_PreheatTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_HeatingTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft_DelayTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-关/开 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_Switch {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_SetTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_PreheatTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_HeatingTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-左(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatLeft2_DelayTime {
            get {
                return ResourceManager.GetString("BRailPreheatLeft2_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-关/开 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_Switch {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_SetTemperature {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_PreheatTime {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_HeatingTime {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨胶板工位-中-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailGlueBoardStationMiddle_DelayTime {
            get {
                return ResourceManager.GetString("BRailGlueBoardStationMiddle_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-关/开 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_Switch {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_SetTemperature {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_PreheatTime {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_HeatingTime {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨点胶工位-中(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailDispensingStationMiddle2_DelayTime {
            get {
                return ResourceManager.GetString("BRailDispensingStationMiddle2_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-关/开 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_Switch {
            get {
                return ResourceManager.GetString("BRailPreheatRight_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatRight_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_SetTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatRight_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailPreheatRight_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailPreheatRight_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_PreheatTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_HeatingTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatRight_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatRight_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight_DelayTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight_DelayTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-关/开 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_Switch {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_Switch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-当前温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_CurrentTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_CurrentTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-设定温度 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_SetTemperature {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_SetTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-温度范围 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_TemperatureRange {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_TemperatureRange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-空闲关闭间隔 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_IdleCloseInterval {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_IdleCloseInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-预热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_PreheatTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_PreheatTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-加热时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_HeatingTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_HeatingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-检测开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_DetectionEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_DetectionEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-工作开启 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_WorkEnabled {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_WorkEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 B轨预热-右(2)-延迟时间 的本地化字符串
        /// </summary>
        internal static string BRailPreheatRight2_DelayTime {
            get {
                return ResourceManager.GetString("BRailPreheatRight2_DelayTime", resourceCulture);
            }
        }
    }
}

