//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.Label {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        internal ResourceNames() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.Label.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string BackColor => ResourceManager.GetString("BackColor", resourceCulture);
        internal static string ForeColor => ResourceManager.GetString("ForeColor", resourceCulture);
        internal static string Label => ResourceManager.GetString("Label", resourceCulture);
        internal static string Opacity => ResourceManager.GetString("Opacity", resourceCulture);
        internal static string Text => ResourceManager.GetString("Text", resourceCulture);
        internal static string Visible => ResourceManager.GetString("Visible", resourceCulture);
        internal static string X => ResourceManager.GetString("X", resourceCulture);
        internal static string Y => ResourceManager.GetString("Y", resourceCulture);
    }
}
