//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.HeatingControlFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.HeatingControlFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色操作 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前温度 的本地化字符串。
        /// </summary>
        internal static string CurrentTemperature {
            get {
                return ResourceManager.GetString("CurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟时间 的本地化字符串。
        /// </summary>
        internal static string DelayTime {
            get {
                return ResourceManager.GetString("DelayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测开启 的本地化字符串。
        /// </summary>
        internal static string DetectionEnabled {
            get {
                return ResourceManager.GetString("DetectionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加热控制 的本地化字符串。
        /// </summary>
        internal static string HeatingControl {
            get {
                return ResourceManager.GetString("HeatingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加热开关 的本地化字符串。
        /// </summary>
        internal static string HeatingSwitch {
            get {
                return ResourceManager.GetString("HeatingSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加热时间 的本地化字符串。
        /// </summary>
        internal static string HeatingTime {
            get {
                return ResourceManager.GetString("HeatingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空闲关闭间隔 的本地化字符串。
        /// </summary>
        internal static string IdleCloseInterval {
            get {
                return ResourceManager.GetString("IdleCloseInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预热时间 的本地化字符串。
        /// </summary>
        internal static string PreheatTime {
            get {
                return ResourceManager.GetString("PreheatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定温度 的本地化字符串。
        /// </summary>
        internal static string SetTemperature {
            get {
                return ResourceManager.GetString("SetTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度范围 的本地化字符串。
        /// </summary>
        internal static string TemperatureRange {
            get {
                return ResourceManager.GetString("TemperatureRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度最大值 的本地化字符串。
        /// </summary>
        internal static string TemperatureRangeMax {
            get {
                return ResourceManager.GetString("TemperatureRangeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度最小值 的本地化字符串。
        /// </summary>
        internal static string TemperatureRangeMin {
            get {
                return ResourceManager.GetString("TemperatureRangeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色操作 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体 的本地化字符串。
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体操作原子 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体操作 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作开启 的本地化字符串。
        /// </summary>
        internal static string WorkEnabled {
            get {
                return ResourceManager.GetString("WorkEnabled", resourceCulture);
            }
        }
    }
}
