//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Griffins.CompUI.SL {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Griffins.CompUI.SL.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 气缸延时 的本地化字符串。
        /// </summary>
        internal static string ViewName_CylinderDelay {
            get {
                return ResourceManager.GetString("ViewName_CylinderDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 双控双限位 的本地化字符串。
        /// </summary>
        internal static string ViewName_DoubleControlDoubleLimit {
            get {
                return ResourceManager.GetString("ViewName_DoubleControlDoubleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机机构 的本地化字符串。
        /// </summary>
        internal static string ViewName_MotorMechanism {
            get {
                return ResourceManager.GetString("ViewName_MotorMechanism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电机速度 的本地化字符串。
        /// </summary>
        internal static string ViewName_MotorSpeed {
            get {
                return ResourceManager.GetString("ViewName_MotorSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上下位机通讯 的本地化字符串。
        /// </summary>
        internal static string ViewName_PcCommunication {
            get {
                return ResourceManager.GetString("ViewName_PcCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规单层轨道类 的本地化字符串。
        /// </summary>
        internal static string ViewName_RegularSingleTrack {
            get {
                return ResourceManager.GetString("ViewName_RegularSingleTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单控双限位 的本地化字符串。
        /// </summary>
        internal static string ViewName_SingleControlDoubleLimit {
            get {
                return ResourceManager.GetString("ViewName_SingleControlDoubleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单控单限位 的本地化字符串。
        /// </summary>
        internal static string ViewName_SingleControlSingleLimit {
            get {
                return ResourceManager.GetString("ViewName_SingleControlSingleLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单层轨道工位 的本地化字符串。
        /// </summary>
        internal static string ViewName_SingleTrackStation {
            get {
                return ResourceManager.GetString("ViewName_SingleTrackStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准直接工作类 的本地化字符串。
        /// </summary>
        internal static string ViewName_StandardDirectWork {
            get {
                return ResourceManager.GetString("ViewName_StandardDirectWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string ViewName_Test {
            get {
                return ResourceManager.GetString("ViewName_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本参数 的本地化字符串。
        /// </summary>
        internal static string ViewName_TrackBasicParam {
            get {
                return ResourceManager.GetString("ViewName_TrackBasicParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道调宽 的本地化字符串。
        /// </summary>
        internal static string ViewName_TrackWidening {
            get {
                return ResourceManager.GetString("ViewName_TrackWidening", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 工位配置 的本地化字符串。
        /// </summary>
        internal static string ViewName_TrackStationConfig {
            get {
                return ResourceManager.GetString("ViewName_TrackStationConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输电机 的本地化字符串。
        /// </summary>
        internal static string ViewName_TransportMotor {
            get {
                return ResourceManager.GetString("ViewName_TransportMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试1 的本地化字符串。
        /// </summary>
        internal static string ViewzName_Test1 {
            get {
                return ResourceManager.GetString("ViewzName_Test1", resourceCulture);
            }
        }
    }
}
