//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.SubMM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.RailWorkStationSubMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 是否有料 的本地化字符串。
        /// </summary>
        public static string IsHaveMaterial {
            get {
                return ResourceManager.GetString("IsHaveMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂配置存在左气缸，但初始化参数未配置 LeftBlockCylinderParams.IOStateGuidList。 的本地化字符串。
        /// </summary>
        public static string LeftCylinderIoMissing {
            get {
                return ResourceManager.GetString("LeftCylinderIoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左气缸状态 的本地化字符串。
        /// </summary>
        public static string LeftCylinderState {
            get {
                return ResourceManager.GetString("LeftCylinderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂配置存在左感应器，但初始化参数未配置 LeftSensorID。 的本地化字符串。
        /// </summary>
        public static string LeftSensorIdMissing {
            get {
                return ResourceManager.GetString("LeftSensorIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左感应器状态 的本地化字符串。
        /// </summary>
        public static string LeftSensorState {
            get {
                return ResourceManager.GetString("LeftSensorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂配置存在接近感应器，但初始化参数未配置 ProximitySensorID。 的本地化字符串。
        /// </summary>
        public static string ProximitySensorIdMissing {
            get {
                return ResourceManager.GetString("ProximitySensorIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道工位 IO 绑定数量校验失败，返回的 IO 实例数量与请求数量不一致。 的本地化字符串。
        /// </summary>
        public static string RailIoBindingCountMismatch {
            get {
                return ResourceManager.GetString("RailIoBindingCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轨道工位 IO 实例数量不匹配，请求 {0} 个，返回 {1} 个。 的本地化字符串。
        /// </summary>
        public static string RailIoInstanceCountMismatchFormat {
            get {
                return ResourceManager.GetString("RailIoInstanceCountMismatchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过交互消息获取轨道工位 IO 实例失败。 的本地化字符串。
        /// </summary>
        public static string RailIoRequestFailed {
            get {
                return ResourceManager.GetString("RailIoRequestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩回 的本地化字符串。
        /// </summary>
        public static string Retract {
            get {
                return ResourceManager.GetString("Retract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂配置存在右气缸，但初始化参数未配置 RightBlockCylinderParams.IOStateGuidList。 的本地化字符串。
        /// </summary>
        public static string RightCylinderIoMissing {
            get {
                return ResourceManager.GetString("RightCylinderIoMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右气缸状态 的本地化字符串。
        /// </summary>
        public static string RightCylinderState {
            get {
                return ResourceManager.GetString("RightCylinderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出厂配置存在右感应器，但初始化参数未配置 RightSensorID。 的本地化字符串。
        /// </summary>
        public static string RightSensorIdMissing {
            get {
                return ResourceManager.GetString("RightSensorIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右感应器状态 的本地化字符串。
        /// </summary>
        public static string RightSensorState {
            get {
                return ResourceManager.GetString("RightSensorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运输速度档位列表不能为空 的本地化字符串。
        /// </summary>
        public static string SpeedNullError {
            get {
                return ResourceManager.GetString("SpeedNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸出 的本地化字符串。
        /// </summary>
        public static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
    }
}
