//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.ProductionInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.ProductionInfo.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总耗胶量.
        /// </summary>
        internal static string BatchTotalDispensedWeight {
            get {
                return ResourceManager.GetString("BatchTotalDispensedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序名称.
        /// </summary>
        internal static string CurrentRecipeName {
            get {
                return ResourceManager.GetString("CurrentRecipeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前阀配方参数.
        /// </summary>
        internal static string CurrentValveRecipe {
            get {
                return ResourceManager.GetString("CurrentValveRecipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已使用时间.
        /// </summary>
        internal static string ElapsedUsageHours {
            get {
                return ResourceManager.GetString("ElapsedUsageHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部称重状态.
        /// </summary>
        internal static string ExternalScaleStatus {
            get {
                return ResourceManager.GetString("ExternalScaleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双轨.
        /// </summary>
        internal static string HasDualLane {
            get {
                return ResourceManager.GetString("HasDualLane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 双阀.
        /// </summary>
        internal static string HasDualValve {
            get {
                return ResourceManager.GetString("HasDualValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除.
        /// </summary>
        internal static string HasLeftIonizer {
            get {
                return ResourceManager.GetString("HasLeftIonizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右静电消除.
        /// </summary>
        internal static string HasRightIonizer {
            get {
                return ResourceManager.GetString("HasRightIonizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用点胶后自动出板.
        /// </summary>
        internal static string IsHoldAfterDispenseEnabled {
            get {
                return ResourceManager.GetString("IsHoldAfterDispenseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀静电消除.
        /// </summary>
        internal static string IsLeftIonizerEnabled {
            get {
                return ResourceManager.GetString("IsLeftIonizerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀自动定量称重.
        /// </summary>
        internal static string IsLeftValveAutoQuantitativeWeighingEnabled {
            get {
                return ResourceManager.GetString("IsLeftValveAutoQuantitativeWeighingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀自动单点称重.
        /// </summary>
        internal static string IsLeftValveAutoShotWeighingEnabled {
            get {
                return ResourceManager.GetString("IsLeftValveAutoShotWeighingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空跑坏板.
        /// </summary>
        internal static string IsNgDryRunEnabled {
            get {
                return ResourceManager.GetString("IsNgDryRunEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀静电消除.
        /// </summary>
        internal static string IsRightIonizerEnabled {
            get {
                return ResourceManager.GetString("IsRightIonizerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀自动定量称重.
        /// </summary>
        internal static string IsRightValveAutoQuantitativeWeighingEnabled {
            get {
                return ResourceManager.GetString("IsRightValveAutoQuantitativeWeighingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀自动单点称重.
        /// </summary>
        internal static string IsRightValveAutoShotWeighingEnabled {
            get {
                return ResourceManager.GetString("IsRightValveAutoShotWeighingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时清洗液泵.
        /// </summary>
        internal static string IsScheduledSolventPumpEnabled {
            get {
                return ResourceManager.GetString("IsScheduledSolventPumpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在清洗液泵.
        /// </summary>
        internal static string IsSolventPumpRunning {
            get {
                return ResourceManager.GetString("IsSolventPumpRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨条码.
        /// </summary>
        internal static string LaneABarcode1 {
            get {
                return ResourceManager.GetString("LaneABarcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨单板时间.
        /// </summary>
        internal static string LaneABoardProcessTime {
            get {
                return ResourceManager.GetString("LaneABoardProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨大板目前产量.
        /// </summary>
        internal static string LaneACurrentBigBoardCount {
            get {
                return ResourceManager.GetString("LaneACurrentBigBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨小板目前产量.
        /// </summary>
        internal static string LaneACurrentSmallBoardCount {
            get {
                return ResourceManager.GetString("LaneACurrentSmallBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨运行周期.
        /// </summary>
        internal static string LaneACycleTime {
            get {
                return ResourceManager.GetString("LaneACycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨点胶时间.
        /// </summary>
        internal static string LaneADispenseTime {
            get {
                return ResourceManager.GetString("LaneADispenseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨进板时间.
        /// </summary>
        internal static string LaneALoadTime {
            get {
                return ResourceManager.GetString("LaneALoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨Mark时间.
        /// </summary>
        internal static string LaneAMarkTime {
            get {
                return ResourceManager.GetString("LaneAMarkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨大板总产量.
        /// </summary>
        internal static string LaneATotalBigBoardCount {
            get {
                return ResourceManager.GetString("LaneATotalBigBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨小板总产量.
        /// </summary>
        internal static string LaneATotalSmallBoardCount {
            get {
                return ResourceManager.GetString("LaneATotalSmallBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A轨出板时间.
        /// </summary>
        internal static string LaneAUnloadTime {
            get {
                return ResourceManager.GetString("LaneAUnloadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨条码.
        /// </summary>
        internal static string LaneBBarcode {
            get {
                return ResourceManager.GetString("LaneBBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨单板时间.
        /// </summary>
        internal static string LaneBBoardProcessTime {
            get {
                return ResourceManager.GetString("LaneBBoardProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨大板目前产量.
        /// </summary>
        internal static string LaneBCurrentBigBoardCount {
            get {
                return ResourceManager.GetString("LaneBCurrentBigBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨小板目前产量.
        /// </summary>
        internal static string LaneBCurrentSmallBoardCount {
            get {
                return ResourceManager.GetString("LaneBCurrentSmallBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨运行周期.
        /// </summary>
        internal static string LaneBCycleTime {
            get {
                return ResourceManager.GetString("LaneBCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨点胶时间.
        /// </summary>
        internal static string LaneBDispenseTime {
            get {
                return ResourceManager.GetString("LaneBDispenseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨进板时间.
        /// </summary>
        internal static string LaneBLoadTime {
            get {
                return ResourceManager.GetString("LaneBLoadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨Mark时间.
        /// </summary>
        internal static string LaneBMarkTime {
            get {
                return ResourceManager.GetString("LaneBMarkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨大板总产量.
        /// </summary>
        internal static string LaneBTotalBigBoardCount {
            get {
                return ResourceManager.GetString("LaneBTotalBigBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨小板总产量.
        /// </summary>
        internal static string LaneBTotalSmallBoardCount {
            get {
                return ResourceManager.GetString("LaneBTotalSmallBoardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B轨出板时间.
        /// </summary>
        internal static string LaneBUnloadTime {
            get {
                return ResourceManager.GetString("LaneBUnloadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀当前胶水余量.
        /// </summary>
        internal static string LeftValveRemainingGlueAmount {
            get {
                return ResourceManager.GetString("LeftValveRemainingGlueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀单点胶重.
        /// </summary>
        internal static string LeftValveShotWeight {
            get {
                return ResourceManager.GetString("LeftValveShotWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左阀胶水总量.
        /// </summary>
        internal static string LeftValveTotalGlueWeight {
            get {
                return ResourceManager.GetString("LeftValveTotalGlueWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行时间.
        /// </summary>
        internal static string MachineRunTime {
            get {
                return ResourceManager.GetString("MachineRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最长使用时间.
        /// </summary>
        internal static string MaxUsageHours {
            get {
                return ResourceManager.GetString("MaxUsageHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产信息.
        /// </summary>
        internal static string ProductionInformation {
            get {
                return ResourceManager.GetString("ProductionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀当前胶水余量.
        /// </summary>
        internal static string RightValveRemainingGlueAmount {
            get {
                return ResourceManager.GetString("RightValveRemainingGlueAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀单点胶重.
        /// </summary>
        internal static string RightValveShotWeight {
            get {
                return ResourceManager.GetString("RightValveShotWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水总量.
        /// </summary>
        internal static string RightValveTotalGlueWeight {
            get {
                return ResourceManager.GetString("RightValveTotalGlueWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产数量.
        /// </summary>
        internal static string TargetProductionCount {
            get {
                return ResourceManager.GetString("TargetProductionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产类型.
        /// </summary>
        internal static string TargetProductionType {
            get {
                return ResourceManager.GetString("TargetProductionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每小时产出.
        /// </summary>
        internal static string Uph {
            get {
                return ResourceManager.GetString("Uph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备使用率.
        /// </summary>
        internal static string UtilizationRate {
            get {
                return ResourceManager.GetString("UtilizationRate", resourceCulture);
            }
        }
    }
}
