//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.VisionSubMachineModules.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.VisionSubMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 通过交互消息获取轴信息失败。 的本地化字符串。
        /// </summary>
        public static string AxisInfosAcquireFailed {
            get {
                return ResourceManager.GetString("AxisInfosAcquireFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到绑定X轴信息: {0} 的本地化字符串。
        /// </summary>
        public static string BindingAxisXInfoNotFound {
            get {
                return ResourceManager.GetString("BindingAxisXInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到绑定Y轴信息: {0} 的本地化字符串。
        /// </summary>
        public static string BindingAxisYInfoNotFound {
            get {
                return ResourceManager.GetString("BindingAxisYInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到绑定Z轴信息: {0} 的本地化字符串。
        /// </summary>
        public static string BindingAxisZInfoNotFound {
            get {
                return ResourceManager.GetString("BindingAxisZInfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置 ChangeCCDOrJetIOGuid，无法获取视觉IO实例。 的本地化字符串。
        /// </summary>
        public static string ChangeCCDOrJetIOGuidNotConfigured {
            get {
                return ResourceManager.GetString("ChangeCCDOrJetIOGuidNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的轴ID无效: {1} 的本地化字符串。
        /// </summary>
        public static string InvalidAxisIdForField {
            get {
                return ResourceManager.GetString("InvalidAxisIdForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人驱动未初始化 的本地化字符串。
        /// </summary>
        public static string RobotDriverNotInitialized {
            get {
                return ResourceManager.GetString("RobotDriverNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时控制命令缺少 ImagePoint 参数 的本地化字符串。
        /// </summary>
        public static string RuntimeCtlCmdImagePointRequired {
            get {
                return ResourceManager.GetString("RuntimeCtlCmdImagePointRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的运行时控制命令: {0} 的本地化字符串。
        /// </summary>
        public static string RuntimeCtlCmdNotSupported {
            get {
                return ResourceManager.GetString("RuntimeCtlCmdNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时控制命令参数不能为空 的本地化字符串。
        /// </summary>
        public static string RuntimeCtlCmdParamRequired {
            get {
                return ResourceManager.GetString("RuntimeCtlCmdParamRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置 TriggerCCDIOGuid，无法获取视觉IO实例。 的本地化字符串。
        /// </summary>
        public static string TriggerCCDIOGuidNotConfigured {
            get {
                return ResourceManager.GetString("TriggerCCDIOGuidNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置视觉模组绑定轴，无法获取RobotDriver。 的本地化字符串。
        /// </summary>
        public static string VisionBindingAxesNotConfigured {
            get {
                return ResourceManager.GetString("VisionBindingAxesNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉驱动未初始化 的本地化字符串。
        /// </summary>
        public static string VisionDriverNotInitialized {
            get {
                return ResourceManager.GetString("VisionDriverNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过交互消息获取视觉IO实例失败。 的本地化字符串。
        /// </summary>
        public static string VisionIOAcquireFailed {
            get {
                return ResourceManager.GetString("VisionIOAcquireFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视觉IO实例列表为空。 的本地化字符串。
        /// </summary>
        public static string VisionIOListEmpty {
            get {
                return ResourceManager.GetString("VisionIOListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过交互消息获取RobotDriver失败。 的本地化字符串。
        /// </summary>
        public static string VisionRobotDriverAcquireFailed {
            get {
                return ResourceManager.GetString("VisionRobotDriverAcquireFailed", resourceCulture);
            }
        }
    }
}
