//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Station.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Station.Server.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动化.
        /// </summary>
        internal static string DevType_AutoMate {
            get {
                return ResourceManager.GetString("DevType_AutoMate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固晶机.
        /// </summary>
        internal static string DevType_DieAttach {
            get {
                return ResourceManager.GetString("DevType_DieAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点胶机.
        /// </summary>
        internal static string DevType_Dispenser {
            get {
                return ResourceManager.GetString("DevType_Dispenser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string DevType_Other {
            get {
                return ResourceManager.GetString("DevType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 印刷机.
        /// </summary>
        internal static string DevType_PringtingPress {
            get {
                return ResourceManager.GetString("DevType_PringtingPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备类型中还存在设备,不可删除.
        /// </summary>
        internal static string Error_HasDevKindInDevType {
            get {
                return ResourceManager.GetString("Error_HasDevKindInDevType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位服务.
        /// </summary>
        internal static string Station_ServerKindName {
            get {
                return ResourceManager.GetString("Station_ServerKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工位子系统.
        /// </summary>
        internal static string Station_SubSysName {
            get {
                return ResourceManager.GetString("Station_SubSysName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基础软件组件.
        /// </summary>
        internal static string SubMecmType_Baseso {
            get {
                return ResourceManager.GetString("SubMecmType_Baseso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        internal static string SubMecmType_Other {
            get {
                return ResourceManager.GetString("SubMecmType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子机械模组.
        /// </summary>
        internal static string SubMecmType_SubMecm {
            get {
                return ResourceManager.GetString("SubMecmType_SubMecm", resourceCulture);
            }
        }
    }
}
