//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.DataMonitor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.DataMonitor.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 数据监控 的本地化字符串。
        /// </summary>
        internal static string DataMonitor {
            get {
                return ResourceManager.GetString("DataMonitor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供阀气压栏状态切换 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressureStatusSwitch {
            get {
                return ResourceManager.GetString("SupplyValvePressureStatusSwitch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供阀气压栏状态名称 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressureStatusName {
            get {
                return ResourceManager.GetString("SupplyValvePressureStatusName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供阀气压值 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressureStatusValue {
            get {
                return ResourceManager.GetString("SupplyValvePressureStatusValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供阀气压单位 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressureStatusUnit {
            get {
                return ResourceManager.GetString("SupplyValvePressureStatusUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供胶气压栏状态切换 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressureStatusSwitch {
            get {
                return ResourceManager.GetString("SupplyGluePressureStatusSwitch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供胶气压栏状态名称 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressureStatusName {
            get {
                return ResourceManager.GetString("SupplyGluePressureStatusName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供胶气压值 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressureStatusValue {
            get {
                return ResourceManager.GetString("SupplyGluePressureStatusValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 供胶气压单位 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressureStatusUnit {
            get {
                return ResourceManager.GetString("SupplyGluePressureStatusUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 喷嘴加热栏状态切换 的本地化字符串。
        /// </summary>
        internal static string NozzleHeatingStatusSwitch {
            get {
                return ResourceManager.GetString("NozzleHeatingStatusSwitch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 喷嘴加热栏状态名称 的本地化字符串。
        /// </summary>
        internal static string NozzleHeatingStatusName {
            get {
                return ResourceManager.GetString("NozzleHeatingStatusName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 喷嘴加热温度值 的本地化字符串。
        /// </summary>
        internal static string NozzleHeatingStatusValue {
            get {
                return ResourceManager.GetString("NozzleHeatingStatusValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 喷嘴加热单位 的本地化字符串。
        /// </summary>
        internal static string NozzleHeatingStatusUnit {
            get {
                return ResourceManager.GetString("NozzleHeatingStatusUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安全门状态 的本地化字符串。
        /// </summary>
        internal static string SafetyDoorStatus {
            get {
                return ResourceManager.GetString("SafetyDoorStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 总气压状态 的本地化字符串。
        /// </summary>
        internal static string TotalPressureStatus {
            get {
                return ResourceManager.GetString("TotalPressureStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清洁布状态 的本地化字符串。
        /// </summary>
        internal static string CleaningClothStatus {
            get {
                return ResourceManager.GetString("CleaningClothStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 双阀模式 的本地化字符串。
        /// </summary>
        internal static string IsDualValve {
            get {
                return ResourceManager.GetString("IsDualValve", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 胶水余量 的本地化字符串。
        /// </summary>
        internal static string GlueRemaining {
            get {
                return ResourceManager.GetString("GlueRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水余量 的本地化字符串。
        /// </summary>
        internal static string LeftGlueRemaining {
            get {
                return ResourceManager.GetString("LeftGlueRemaining", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 校正 的本地化字符串。
        /// </summary>
        internal static string Calibration {
            get {
                return ResourceManager.GetString("Calibration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀校正 的本地化字符串。
        /// </summary>
        internal static string LeftCalibration {
            get {
                return ResourceManager.GetString("LeftCalibration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 阀体值 的本地化字符串。
        /// </summary>
        internal static string ValveBodyValue {
            get {
                return ResourceManager.GetString("ValveBodyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀阀体值 的本地化字符串。
        /// </summary>
        internal static string LeftValveBodyValue {
            get {
                return ResourceManager.GetString("LeftValveBodyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 密封圈值 的本地化字符串。
        /// </summary>
        internal static string SealingRingValue {
            get {
                return ResourceManager.GetString("SealingRingValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀密封圈值 的本地化字符串。
        /// </summary>
        internal static string LeftSealingRingValue {
            get {
                return ResourceManager.GetString("LeftSealingRingValue", resourceCulture);
            }
        }
    }
}
