//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.PushRodSubMachineModules.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.PushRodSubMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 缺少或无效的 MaxSpeed 的本地化字符串。
        /// </summary>
        public static string MaxSpeedInvalid {
            get {
                return ResourceManager.GetString("MaxSpeedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少或无效的 PushDistance 的本地化字符串。
        /// </summary>
        public static string PushDistanceInvalid {
            get {
                return ResourceManager.GetString("PushDistanceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推杆推出超时 的本地化字符串。
        /// </summary>
        public static string PushRodExtendTimeout {
            get {
                return ResourceManager.GetString("PushRodExtendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推杆轴位置缓存尚未初始化，请先等待 PositionChanged 事件更新位置。 的本地化字符串。
        /// </summary>
        public static string PushRodPositionCacheNotInitialized {
            get {
                return ResourceManager.GetString("PushRodPositionCacheNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推杆缩回超时 的本地化字符串。
        /// </summary>
        public static string PushRodRetractTimeout {
            get {
                return ResourceManager.GetString("PushRodRetractTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未获取到推杆机械手驱动响应。 的本地化字符串。
        /// </summary>
        public static string PushRodRobotDriverResponseMissing {
            get {
                return ResourceManager.GetString("PushRodRobotDriverResponseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推杆机械手驱动响应中未包含可用的 RobotDriver。 的本地化字符串。
        /// </summary>
        public static string PushRodRobotDriverUnavailable {
            get {
                return ResourceManager.GetString("PushRodRobotDriverUnavailable", resourceCulture);
            }
        }
    }
}
