//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.CommunicationFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.CommunicationFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 后停状态 的本地化字符串。
        /// </summary>
        internal static string AfterStop {
            get {
                return ResourceManager.GetString("AfterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色操作 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信 的本地化字符串。
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点胶模式 的本地化字符串。
        /// </summary>
        internal static string DispenseMode {
            get {
                return ResourceManager.GetString("DispenseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点胶时间(ms) 的本地化字符串。
        /// </summary>
        internal static string DispenseTime {
            get {
                return ResourceManager.GetString("DispenseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 画点次数 的本地化字符串。
        /// </summary>
        internal static string DotCount {
            get {
                return ResourceManager.GetString("DotCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撞击时间(ms) 的本地化字符串。
        /// </summary>
        internal static string ImpactTime {
            get {
                return ResourceManager.GetString("ImpactTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间歇时间(ms) 的本地化字符串。
        /// </summary>
        internal static string IntermittentTime {
            get {
                return ResourceManager.GetString("IntermittentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抬起时间(ms) 的本地化字符串。
        /// </summary>
        internal static string RaiseTime {
            get {
                return ResourceManager.GetString("RaiseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色操作 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体 的本地化字符串。
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体操作原子 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字字体操作 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总次数 的本地化字符串。
        /// </summary>
        internal static string TotalCount {
            get {
                return ResourceManager.GetString("TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电压比(%) 的本地化字符串。
        /// </summary>
        internal static string VoltageRatio {
            get {
                return ResourceManager.GetString("VoltageRatio", resourceCulture);
            }
        }
    }
}
