//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.StationFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.StationFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 工位数据组操作原子 的本地化字符串。
        /// </summary>
        internal static string DataGroup_MapOprtCellName {
            get {
                return ResourceManager.GetString("DataGroup_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位有料 的本地化字符串。
        /// </summary>
        internal static string HasBoard {
            get {
                return ResourceManager.GetString("HasBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位有料操作 的本地化字符串。
        /// </summary>
        internal static string HasBoard_MapOprtName {
            get {
                return ResourceManager.GetString("HasBoard_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置左挡板 的本地化字符串。
        /// </summary>
        internal static string HasLeftJacking {
            get {
                return ResourceManager.GetString("HasLeftJacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置左挡板操作 的本地化字符串。
        /// </summary>
        internal static string HasLeftJacking_MapOprtName {
            get {
                return ResourceManager.GetString("HasLeftJacking_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置右挡板 的本地化字符串。
        /// </summary>
        internal static string HasRightJacking {
            get {
                return ResourceManager.GetString("HasRightJacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置右挡板操作 的本地化字符串。
        /// </summary>
        internal static string HasRightJacking_MapOprtName {
            get {
                return ResourceManager.GetString("HasRightJacking_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左挡板状态 的本地化字符串。
        /// </summary>
        internal static string LeftJackingState {
            get {
                return ResourceManager.GetString("LeftJackingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左挡板状态操作 的本地化字符串。
        /// </summary>
        internal static string LeftJackingState_MapOprtName {
            get {
                return ResourceManager.GetString("LeftJackingState_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左感应器状态 的本地化字符串。
        /// </summary>
        internal static string LeftSensorStatus {
            get {
                return ResourceManager.GetString("LeftSensorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左感应器状态操作 的本地化字符串。
        /// </summary>
        internal static string LeftSensorStatus_MapOprtName {
            get {
                return ResourceManager.GetString("LeftSensorStatus_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右挡板状态 的本地化字符串。
        /// </summary>
        internal static string RightJackingState {
            get {
                return ResourceManager.GetString("RightJackingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右挡板状态操作 的本地化字符串。
        /// </summary>
        internal static string RightJackingState_MapOprtName {
            get {
                return ResourceManager.GetString("RightJackingState_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右感应器状态 的本地化字符串。
        /// </summary>
        internal static string RightSensorStatus {
            get {
                return ResourceManager.GetString("RightSensorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右感应器状态操作 的本地化字符串。
        /// </summary>
        internal static string RightSensorStatus_MapOprtName {
            get {
                return ResourceManager.GetString("RightSensorStatus_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工位 的本地化字符串。
        /// </summary>
        internal static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
    }
}
