//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainFrame {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainFrame.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 动态加载固子页面或子页面容器 的本地化字符串。
        /// </summary>
        internal static string Dynamic {
            get {
                return ResourceManager.GetString("Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转到上级页面 的本地化字符串。
        /// </summary>
        internal static string GoToParentPage {
            get {
                return ResourceManager.GetString("GoToParentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到子页面 的本地化字符串。
        /// </summary>
        internal static string GotoSubPage {
            get {
                return ResourceManager.GetString("GotoSubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换到子页面容器 的本地化字符串。
        /// </summary>
        internal static string GotoSubPageContainer {
            get {
                return ResourceManager.GetString("GotoSubPageContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置子页面 的本地化字符串。
        /// </summary>
        internal static string NoCfgSubPageID {
            get {
                return ResourceManager.GetString("NoCfgSubPageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到客户端页面种类信息 的本地化字符串。
        /// </summary>
        internal static string NoClientPageInfo {
            get {
                return ResourceManager.GetString("NoClientPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置子页面容器实例 的本地化字符串。
        /// </summary>
        internal static string NoContainerInstanceID {
            get {
                return ResourceManager.GetString("NoContainerInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置页面 的本地化字符串。
        /// </summary>
        internal static string NoPageID {
            get {
                return ResourceManager.GetString("NoPageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定页面信息 的本地化字符串。
        /// </summary>
        internal static string NoPageInfo {
            get {
                return ResourceManager.GetString("NoPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定子页面容器实例 的本地化字符串。
        /// </summary>
        internal static string NoSubPageContainerInstance {
            get {
                return ResourceManager.GetString("NoSubPageContainerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到子页面信息 的本地化字符串。
        /// </summary>
        internal static string NoSubPageInfo {
            get {
                return ResourceManager.GetString("NoSubPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的菜单执行命令种类 的本地化字符串。
        /// </summary>
        internal static string NoSurportMenuCmdKind {
            get {
                return ResourceManager.GetString("NoSurportMenuCmdKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到任何页面信息 的本地化字符串。
        /// </summary>
        internal static string NothingPageInfo {
            get {
                return ResourceManager.GetString("NothingPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到任何子页面容器实例 的本地化字符串。
        /// </summary>
        internal static string NothingSubPageContainerInstance {
            get {
                return ResourceManager.GetString("NothingSubPageContainerInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到任何子页面信息 的本地化字符串。
        /// </summary>
        internal static string NothingSubPageInfo {
            get {
                return ResourceManager.GetString("NothingSubPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的顶部菜单 的本地化字符串。
        /// </summary>
        internal static string NoTopMenuButton {
            get {
                return ResourceManager.GetString("NoTopMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到指定子页面 的本地化字符串。
        /// </summary>
        internal static string NoubPageInfo {
            get {
                return ResourceManager.GetString("NoubPageInfo", resourceCulture);
            }
        }
    }
}
