//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.AuxiliaryInfoFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.AuxiliaryInfoFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助信息.
        /// </summary>
        public static string AuxiliaryInfo {
            get {
                return ResourceManager.GetString("AuxiliaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色操作原子.
        /// </summary>
        public static string BackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色操作.
        /// </summary>
        public static string BackColor_MapOprtName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备ID.
        /// </summary>
        public static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备名称.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 胶水名称.
        /// </summary>
        public static string GlueName {
            get {
                return ResourceManager.GetString("GlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地址.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac地址.
        /// </summary>
        public static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下线.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上线.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 压电阀序号.
        /// </summary>
        public static string PiezoValveSerialNo {
            get {
                return ResourceManager.GetString("PiezoValveSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 产品信息.
        /// </summary>
        public static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序名称.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水生产批次号.
        /// </summary>
        public static string RightValveGlueBatchNo {
            get {
                return ResourceManager.GetString("RightValveGlueBatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水信息.
        /// </summary>
        public static string RightValveGlueInfo {
            get {
                return ResourceManager.GetString("RightValveGlueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水制造料号.
        /// </summary>
        public static string RightValveGlueMaterialNo {
            get {
                return ResourceManager.GetString("RightValveGlueMaterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水包装ID.
        /// </summary>
        public static string RightValveGluePackageId {
            get {
                return ResourceManager.GetString("RightValveGluePackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右阀胶水生产日期.
        /// </summary>
        public static string RightValveGlueProdDate {
            get {
                return ResourceManager.GetString("RightValveGlueProdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存参数.
        /// </summary>
        public static string SaveParams {
            get {
                return ResourceManager.GetString("SaveParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本颜色操作原子.
        /// </summary>
        public static string TextColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本颜色操作.
        /// </summary>
        public static string TextColor_MapOprtName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体.
        /// </summary>
        public static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体操作原子.
        /// </summary>
        public static string TextFont_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字字体操作.
        /// </summary>
        public static string TextFont_MapOprtName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阀ID.
        /// </summary>
        public static string ValveId {
            get {
                return ResourceManager.GetString("ValveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验程序.
        /// </summary>
        public static string VerifyProgram {
            get {
                return ResourceManager.GetString("VerifyProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工单号.
        /// </summary>
        public static string WorkOrderNo {
            get {
                return ResourceManager.GetString("WorkOrderNo", resourceCulture);
            }
        }
    }
}
