//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSXLMM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestSXLMM.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 容器名称 的本地化字符串。
        /// </summary>
        internal static string ContainerName {
            get {
                return ResourceManager.GetString("ContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器编号 的本地化字符串。
        /// </summary>
        internal static string ContainerNo {
            get {
                return ResourceManager.GetString("ContainerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空料 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有料 的本地化字符串。
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒感应状态 的本地化字符串。
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒气缸状态 的本地化字符串。
        /// </summary>
        internal static string MaterialBoxCylinderStatus {
            get {
                return ResourceManager.GetString("MaterialBoxCylinderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒名称 的本地化字符串。
        /// </summary>
        internal static string MaterialBoxName {
            get {
                return ResourceManager.GetString("MaterialBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒编号 的本地化字符串。
        /// </summary>
        internal static string MaterialBoxID {
            get {
                return ResourceManager.GetString("MaterialBoxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料盒列表 的本地化字符串。
        /// </summary>
        internal static string MaterialBoxs {
            get {
                return ResourceManager.GetString("MaterialBoxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器列表 的本地化字符串。
        /// </summary>
        internal static string MaterialContainers {
            get {
                return ResourceManager.GetString("MaterialContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料槽状态 的本地化字符串。
        /// </summary>
        internal static string MaterialStatus {
            get {
                return ResourceManager.GetString("MaterialStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性1 的本地化字符串。
        /// </summary>
        internal static string Prop_1 {
            get {
                return ResourceManager.GetString("Prop_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性2 的本地化字符串。
        /// </summary>
        internal static string Prop_2 {
            get {
                return ResourceManager.GetString("Prop_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料槽编号 的本地化字符串。
        /// </summary>
        internal static string SlotID {
            get {
                return ResourceManager.GetString("SlotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料槽列表 的本地化字符串。
        /// </summary>
        internal static string SlotObjs {
            get {
                return ResourceManager.GetString("SlotObjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子属性1 的本地化字符串。
        /// </summary>
        internal static string SubProp_1 {
            get {
                return ResourceManager.GetString("SubProp_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子属性2 的本地化字符串。
        /// </summary>
        internal static string SubProp_2 {
            get {
                return ResourceManager.GetString("SubProp_2", resourceCulture);
            }
        }
    }
}
