//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.DataMonitorFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.DataMonitorFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环次数 的本地化字符串。
        /// </summary>
        internal static string CycleCount {
            get {
                return ResourceManager.GetString("CycleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据监控 的本地化字符串。
        /// </summary>
        internal static string DataMonitor {
            get {
                return ResourceManager.GetString("DataMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监控信息 的本地化字符串。
        /// </summary>
        internal static string MonitorInfo {
            get {
                return ResourceManager.GetString("MonitorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷嘴加热 的本地化字符串。
        /// </summary>
        internal static string NozzleHeating {
            get {
                return ResourceManager.GetString("NozzleHeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷嘴加热值 的本地化字符串。
        /// </summary>
        internal static string NozzleHeatingValue {
            get {
                return ResourceManager.GetString("NozzleHeatingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压力 的本地化字符串。
        /// </summary>
        internal static string Pressure {
            get {
                return ResourceManager.GetString("Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间 的本地化字符串。
        /// </summary>
        internal static string RunningTime {
            get {
                return ResourceManager.GetString("RunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供胶气压 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressure {
            get {
                return ResourceManager.GetString("SupplyGluePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供胶气压值 的本地化字符串。
        /// </summary>
        internal static string SupplyGluePressureValue {
            get {
                return ResourceManager.GetString("SupplyGluePressureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供阀气压 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressure {
            get {
                return ResourceManager.GetString("SupplyValvePressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供阀气压值 的本地化字符串。
        /// </summary>
        internal static string SupplyValvePressureValue {
            get {
                return ResourceManager.GetString("SupplyValvePressureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统状态 的本地化字符串。
        /// </summary>
        internal static string SystemStatus {
            get {
                return ResourceManager.GetString("SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度 的本地化字符串。
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本颜色 的本地化字符串。
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本字体 的本地化字符串。
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
    }
}
