//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.ProductionInformationFuncCtlMapCell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.ProductionInformationFuncCtlMapCell.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产信息数据.
        /// </summary>
        internal static string Datas {
            get {
                return ResourceManager.GetString("Datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产信息数据操作原子.
        /// </summary>
        internal static string Datas_MapOprtCellName {
            get {
                return ResourceManager.GetString("Datas_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产信息数据操作.
        /// </summary>
        internal static string Datas_MapOprtName {
            get {
                return ResourceManager.GetString("Datas_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除装置.
        /// </summary>
        internal static string HasLeftIonizer {
            get {
                return ResourceManager.GetString("HasLeftIonizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除装置操作原子.
        /// </summary>
        internal static string HasLeftIonizer_MapOprtCellName {
            get {
                return ResourceManager.GetString("HasLeftIonizer_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除装置操作.
        /// </summary>
        internal static string HasLeftIonizer_MapOprtName {
            get {
                return ResourceManager.GetString("HasLeftIonizer_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用点胶后自动出板.
        /// </summary>
        internal static string IsHoldAfterDispenseEnabled {
            get {
                return ResourceManager.GetString("IsHoldAfterDispenseEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用点胶后自动出板原子操作.
        /// </summary>
        internal static string IsHoldAfterDispenseEnabled_MapOprtCellName {
            get {
                return ResourceManager.GetString("IsHoldAfterDispenseEnabled_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用点胶后自动出板操作.
        /// </summary>
        internal static string IsHoldAfterDispenseEnabled_MapOprtName {
            get {
                return ResourceManager.GetString("IsHoldAfterDispenseEnabled_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除开关.
        /// </summary>
        internal static string IsLeftIonizerEnabled {
            get {
                return ResourceManager.GetString("IsLeftIonizerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除开关操作原子.
        /// </summary>
        internal static string IsLeftIonizerEnabled_MapOprtCellName {
            get {
                return ResourceManager.GetString("IsLeftIonizerEnabled_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左静电消除开关操作.
        /// </summary>
        internal static string IsLeftIonizerEnabled_MapOprtName {
            get {
                return ResourceManager.GetString("IsLeftIonizerEnabled_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右静电消除开关.
        /// </summary>
        internal static string IsRightIonizerEnabled {
            get {
                return ResourceManager.GetString("IsRightIonizerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右静电消除开关操作原子.
        /// </summary>
        internal static string IsRightIonizerEnabled_MapOprtCellName {
            get {
                return ResourceManager.GetString("IsRightIonizerEnabled_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右静电消除开关操作.
        /// </summary>
        internal static string IsRightIonizerEnabled_MapOprtName {
            get {
                return ResourceManager.GetString("IsRightIonizerEnabled_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时清洗液泵.
        /// </summary>
        internal static string IsScheduledSolventPumpEnabled {
            get {
                return ResourceManager.GetString("IsScheduledSolventPumpEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时清洗液泵操作原子.
        /// </summary>
        internal static string IsScheduledSolventPumpEnabled_MapOprtCellName {
            get {
                return ResourceManager.GetString("IsScheduledSolventPumpEnabled_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定时清洗液泵操作.
        /// </summary>
        internal static string IsScheduledSolventPumpEnabled_MapOprtName {
            get {
                return ResourceManager.GetString("IsScheduledSolventPumpEnabled_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生产信息.
        /// </summary>
        internal static string ProductionInformation {
            get {
                return ResourceManager.GetString("ProductionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产数量.
        /// </summary>
        internal static string TargetProductionCount {
            get {
                return ResourceManager.GetString("TargetProductionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产数量操作原子.
        /// </summary>
        internal static string TargetProductionCount_MapOprtCellName {
            get {
                return ResourceManager.GetString("TargetProductionCount_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产数量操作.
        /// </summary>
        internal static string TargetProductionCount_MapOprtName {
            get {
                return ResourceManager.GetString("TargetProductionCount_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产类型.
        /// </summary>
        internal static string TargetProductionType {
            get {
                return ResourceManager.GetString("TargetProductionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产类型操作原子.
        /// </summary>
        internal static string TargetProductionType_MapOprtCellName {
            get {
                return ResourceManager.GetString("TargetProductionType_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标生产类型操作.
        /// </summary>
        internal static string TargetProductionType_MapOprtName {
            get {
                return ResourceManager.GetString("TargetProductionType_MapOprtName", resourceCulture);
            }
        }
    }
}
