//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.SubMM {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.RailAdjustWidthSubMachineModules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 未配置后轨调宽轴绑定。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthBackRailAxisBindingMissing {
            get {
                return ResourceManager.GetString("RailAdjustWidthBackRailAxisBindingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取后轨调宽机械手驱动响应失败。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthBackRailRobotDriverResponseMissing {
            get {
                return ResourceManager.GetString("RailAdjustWidthBackRailRobotDriverResponseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取后轨调宽机械手驱动失败。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthBackRailRobotDriverUnavailable {
            get {
                return ResourceManager.GetString("RailAdjustWidthBackRailRobotDriverUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未配置前轨调宽轴绑定。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthFrontRailAxisBindingMissing {
            get {
                return ResourceManager.GetString("RailAdjustWidthFrontRailAxisBindingMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取前轨调宽机械手驱动响应失败。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthFrontRailRobotDriverResponseMissing {
            get {
                return ResourceManager.GetString("RailAdjustWidthFrontRailRobotDriverResponseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取前轨调宽机械手驱动失败。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthFrontRailRobotDriverUnavailable {
            get {
                return ResourceManager.GetString("RailAdjustWidthFrontRailRobotDriverUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可用的回原点运动指令类型。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthHomeInstructionUnavailable {
            get {
                return ResourceManager.GetString("RailAdjustWidthHomeInstructionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知的边轨ID 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthInvalidRailID {
            get {
                return ResourceManager.GetString("RailAdjustWidthInvalidRailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标调宽超出允许范围。 的本地化字符串。
        /// </summary>
        public static string RailAdjustWidthTargetWidthOutOfRange {
            get {
                return ResourceManager.GetString("RailAdjustWidthTargetWidthOutOfRange", resourceCulture);
            }
        }
    }
}
