//------------------------------------------------------------------------------
// <auto-generated>
//     濮濄倓鍞惍浣烘暠瀹搞儱鍙块悽鐔稿灇閵?//     鏉╂劘顢戦弮鍓佸閺?4.0.30319.42000
//
//     鐎佃顒濋弬鍥︽閻ㄥ嫭娲块弨鐟板讲閼虫垝绱扮€佃壈鍤ф稉宥嗩劀绾喚娈戠悰灞艰礋閿涘苯鑻熸稉鏂款洤閺?//     闁插秵鏌婇悽鐔稿灇娴狅絿鐖滈敍宀冪箹娴滄稒娲块弨鐟扮殺娴兼矮娑径渚库偓?// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.Station
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.Station.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string Station
        {
            get
            {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }

        internal static string LeftHasBoard
        {
            get
            {
                return ResourceManager.GetString("LeftHasBoard", resourceCulture);
            }
        }

        internal static string RightHasBoard
        {
            get
            {
                return ResourceManager.GetString("RightHasBoard", resourceCulture);
            }
        }

        internal static string ShowLeftSensorImage
        {
            get
            {
                return ResourceManager.GetString("ShowLeftSensorImage", resourceCulture);
            }
        }

        internal static string ShowRightSensorImage
        {
            get
            {
                return ResourceManager.GetString("ShowRightSensorImage", resourceCulture);
            }
        }

        internal static string HasBoard
        {
            get
            {
                return ResourceManager.GetString("HasBoard", resourceCulture);
            }
        }
    }
}
