//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Griffins.Map.CtlMapCell.Generic {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceA() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Griffins.Map.CtlMapCell.Generic.ResourceA", typeof(ResourceA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 实例别名 的本地化字符串。
        /// </summary>
        internal static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实例别名操作原子 的本地化字符串。
        /// </summary>
        internal static string Alias_MapOprtCellName {
            get {
                return ResourceManager.GetString("Alias_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名操作 的本地化字符串。
        /// </summary>
        internal static string Alias_MapOprtName {
            get {
                return ResourceManager.GetString("Alias_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮背景颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮背景颜色操作 的本地化字符串。
        /// </summary>
        internal static string BackColor_MapOprtName {
            get {
                return ResourceManager.GetString("BackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮背景图元操作原子 的本地化字符串。
        /// </summary>
        internal static string BackgroundImage_MapOprtCellName {
            get {
                return ResourceManager.GetString("BackgroundImage_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮背景图元操作 的本地化字符串。
        /// </summary>
        internal static string BackgroundImage_MapOprtName {
            get {
                return ResourceManager.GetString("BackgroundImage_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮 的本地化字符串。
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名称 的本地化字符串。
        /// </summary>
        internal static string ButtonName {
            get {
                return ResourceManager.GetString("ButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名称操作原子 的本地化字符串。
        /// </summary>
        internal static string ButtonName_MapOprtCellName {
            get {
                return ResourceManager.GetString("ButtonName_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮名称操作 的本地化字符串。
        /// </summary>
        internal static string ButtonName_MapOprtName {
            get {
                return ResourceManager.GetString("ButtonName_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式1 的本地化字符串。
        /// </summary>
        internal static string ButtonStyle1 {
            get {
                return ResourceManager.GetString("ButtonStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列间距 的本地化字符串。
        /// </summary>
        internal static string ColumnSpacing {
            get {
                return ResourceManager.GetString("ColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列间距操作原子 的本地化字符串。
        /// </summary>
        internal static string ColumnSpacing_MapOprtCellName {
            get {
                return ResourceManager.GetString("ColumnSpacing_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列间距操作 的本地化字符串。
        /// </summary>
        internal static string ColumnSpacing_MapOprtName {
            get {
                return ResourceManager.GetString("ColumnSpacing_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉框 的本地化字符串。
        /// </summary>
        internal static string ComboBoxName {
            get {
                return ResourceManager.GetString("ComboBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件类型 的本地化字符串。
        /// </summary>
        internal static string CompTypeID {
            get {
                return ResourceManager.GetString("CompTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面类型操作原子 的本地化字符串。
        /// </summary>
        internal static string CompTypeID_MapOprtCellName {
            get {
                return ResourceManager.GetString("CompTypeID_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组件类型操作 的本地化字符串。
        /// </summary>
        internal static string CompTypeID_MapOprtName {
            get {
                return ResourceManager.GetString("CompTypeID_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器 的本地化字符串。
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前图像 的本地化字符串。
        /// </summary>
        internal static string CurImgKey {
            get {
                return ResourceManager.GetString("CurImgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值改变事件 的本地化字符串。
        /// </summary>
        internal static string Event_ValueChanged {
            get {
                return ResourceManager.GetString("Event_ValueChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        internal static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像控件 的本地化字符串。
        /// </summary>
        internal static string ImageControl {
            get {
                return ResourceManager.GetString("ImageControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像组 的本地化字符串。
        /// </summary>
        internal static string ImageList {
            get {
                return ResourceManager.GetString("ImageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像列表控件 的本地化字符串。
        /// </summary>
        internal static string ImageListControl {
            get {
                return ResourceManager.GetString("ImageListControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮图片定位方式操作原子 的本地化字符串。
        /// </summary>
        internal static string ImageSizeMode_MapOprtCellName {
            get {
                return ResourceManager.GetString("ImageSizeMode_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮图片定位方式操作 的本地化字符串。
        /// </summary>
        internal static string ImageSizeMode_MapOprtName {
            get {
                return ResourceManager.GetString("ImageSizeMode_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string Lable {
            get {
                return ResourceManager.GetString("Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签背景颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string LableBackColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("LableBackColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签背景颜色操作 的本地化字符串。
        /// </summary>
        internal static string LableBackColor_MapOprtName {
            get {
                return ResourceManager.GetString("LableBackColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string LableColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("LableColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签颜色操作 的本地化字符串。
        /// </summary>
        internal static string LableColor_MapOprtName {
            get {
                return ResourceManager.GetString("LableColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式1 的本地化字符串。
        /// </summary>
        internal static string LableStyle1 {
            get {
                return ResourceManager.GetString("LableStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签值 的本地化字符串。
        /// </summary>
        internal static string LableValue_MapOprtCellName {
            get {
                return ResourceManager.GetString("LableValue_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签值操作 的本地化字符串。
        /// </summary>
        internal static string LableValue_MapOprtName {
            get {
                return ResourceManager.GetString("LableValue_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数值编辑 的本地化字符串。
        /// </summary>
        internal static string NumUpDown {
            get {
                return ResourceManager.GetString("NumUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象监控 的本地化字符串。
        /// </summary>
        internal static string ObjectMonitor {
            get {
                return ResourceManager.GetString("ObjectMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象显示 的本地化字符串。
        /// </summary>
        internal static string ObjectValueView {
            get {
                return ResourceManager.GetString("ObjectValueView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面类型ID 的本地化字符串。
        /// </summary>
        internal static string PageTypeID {
            get {
                return ResourceManager.GetString("PageTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面类型iD操作原子 的本地化字符串。
        /// </summary>
        internal static string PageTypeID_MapOprtCellName {
            get {
                return ResourceManager.GetString("PageTypeID_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面类型操作 的本地化字符串。
        /// </summary>
        internal static string PageTypeID_MapOprtName {
            get {
                return ResourceManager.GetString("PageTypeID_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panel容器 的本地化字符串。
        /// </summary>
        internal static string PanelContainer {
            get {
                return ResourceManager.GetString("PanelContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式1 的本地化字符串。
        /// </summary>
        internal static string PanelStyle1 {
            get {
                return ResourceManager.GetString("PanelStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步长 的本地化字符串。
        /// </summary>
        internal static string Prop_Increment {
            get {
                return ResourceManager.GetString("Prop_Increment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大值 的本地化字符串。
        /// </summary>
        internal static string Prop_Maximum {
            get {
                return ResourceManager.GetString("Prop_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小值 的本地化字符串。
        /// </summary>
        internal static string Prop_Minimum {
            get {
                return ResourceManager.GetString("Prop_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向 的本地化字符串。
        /// </summary>
        internal static string Prop_Orientation {
            get {
                return ResourceManager.GetString("Prop_Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string Prop_Value {
            get {
                return ResourceManager.GetString("Prop_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示边框 的本地化字符串。
        /// </summary>
        internal static string ShowBorder {
            get {
                return ResourceManager.GetString("ShowBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示边框操作原子 的本地化字符串。
        /// </summary>
        internal static string ShowBorder_MapOprtCellName {
            get {
                return ResourceManager.GetString("ShowBorder_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示边框操作 的本地化字符串。
        /// </summary>
        internal static string ShowBorder_MapOprtName {
            get {
                return ResourceManager.GetString("ShowBorder_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滑块 的本地化字符串。
        /// </summary>
        internal static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本按钮 的本地化字符串。
        /// </summary>
        internal static string TextButton {
            get {
                return ResourceManager.GetString("TextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式1 的本地化字符串。
        /// </summary>
        internal static string TextButtonStyle1 {
            get {
                return ResourceManager.GetString("TextButtonStyle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文字颜色操作原子 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文本颜色操作 的本地化字符串。
        /// </summary>
        internal static string TextColor_MapOprtName {
            get {
                return ResourceManager.GetString("TextColor_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本字体 的本地化字符串。
        /// </summary>
        internal static string TextFont {
            get {
                return ResourceManager.GetString("TextFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文字字体操作原子 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文本字体操作 的本地化字符串。
        /// </summary>
        internal static string TextFont_MapOprtName {
            get {
                return ResourceManager.GetString("TextFont_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本值 的本地化字符串。
        /// </summary>
        internal static string TextValue {
            get {
                return ResourceManager.GetString("TextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本值操作原子 的本地化字符串。
        /// </summary>
        internal static string TextValue_MapOprtCellName {
            get {
                return ResourceManager.GetString("TextValue_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本值操作 的本地化字符串。
        /// </summary>
        internal static string TextValue_MapOprtName {
            get {
                return ResourceManager.GetString("TextValue_MapOprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值列表 的本地化字符串。
        /// </summary>
        internal static string ValueList {
            get {
                return ResourceManager.GetString("ValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面ID 的本地化字符串。
        /// </summary>
        internal static string ViewID {
            get {
                return ResourceManager.GetString("ViewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面ID操作原子 的本地化字符串。
        /// </summary>
        internal static string ViewID_MapOprtCellName {
            get {
                return ResourceManager.GetString("ViewID_MapOprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 界面ID操作 的本地化字符串。
        /// </summary>
        internal static string ViewID_MapOprtName {
            get {
                return ResourceManager.GetString("ViewID_MapOprtName", resourceCulture);
            }
        }
    }
}
