//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.MapCell.Generic.IconButton {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_IconButton {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_IconButton() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.MapCell.Generic.Control.MapCell_IconButton_New.Resource_IconButton", typeof(Resource_IconButton).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        public static string Btn_BackgroundColor_Name {
            get {
                return ResourceManager.GetString("Btn_BackgroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色更新 的本地化字符串。
        /// </summary>
        public static string Btn_BackgroundColor_OprtName {
            get {
                return ResourceManager.GetString("Btn_BackgroundColor_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框颜色 的本地化字符串。
        /// </summary>
        public static string Btn_BorderBrush_Name {
            get {
                return ResourceManager.GetString("Btn_BorderBrush_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框颜色更新 的本地化字符串。
        /// </summary>
        public static string Btn_BorderBrush_OprtName {
            get {
                return ResourceManager.GetString("Btn_BorderBrush_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框厚度 的本地化字符串。
        /// </summary>
        public static string Btn_BorderThickness_Name {
            get {
                return ResourceManager.GetString("Btn_BorderThickness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框厚度更新 的本地化字符串。
        /// </summary>
        public static string Btn_BorderThickness_OprtName {
            get {
                return ResourceManager.GetString("Btn_BorderThickness_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文本 的本地化字符串。
        /// </summary>
        public static string Btn_ButtonText_Name {
            get {
                return ResourceManager.GetString("Btn_ButtonText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮文本更新 的本地化字符串。
        /// </summary>
        public static string Btn_ButtonText_OprtName {
            get {
                return ResourceManager.GetString("Btn_ButtonText_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆角大小 的本地化字符串。
        /// </summary>
        public static string Btn_CornerRadius_Name {
            get {
                return ResourceManager.GetString("Btn_CornerRadius_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆角大小更新 的本地化字符串。
        /// </summary>
        public static string Btn_CornerRadius_OprtName {
            get {
                return ResourceManager.GetString("Btn_CornerRadius_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标样式 的本地化字符串。
        /// </summary>
        public static string Btn_CursorType_Name {
            get {
                return ResourceManager.GetString("Btn_CursorType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标样式更新 的本地化字符串。
        /// </summary>
        public static string Btn_CursorType_OprtName {
            get {
                return ResourceManager.GetString("Btn_CursorType_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮数据设置原子 的本地化字符串。
        /// </summary>
        public static string Btn_DataGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Btn_DataGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体族 的本地化字符串。
        /// </summary>
        public static string Btn_FontFamily_Name {
            get {
                return ResourceManager.GetString("Btn_FontFamily_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体族更新 的本地化字符串。
        /// </summary>
        public static string Btn_FontFamily_OprtName {
            get {
                return ResourceManager.GetString("Btn_FontFamily_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮字体排版原子 的本地化字符串。
        /// </summary>
        public static string Btn_FontGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Btn_FontGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        public static string Btn_FontSize_Name {
            get {
                return ResourceManager.GetString("Btn_FontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号更新 的本地化字符串。
        /// </summary>
        public static string Btn_FontSize_OprtName {
            get {
                return ResourceManager.GetString("Btn_FontSize_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字颜色 的本地化字符串。
        /// </summary>
        public static string Btn_ForegroundColor_Name {
            get {
                return ResourceManager.GetString("Btn_ForegroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字颜色更新 的本地化字符串。
        /// </summary>
        public static string Btn_ForegroundColor_OprtName {
            get {
                return ResourceManager.GetString("Btn_ForegroundColor_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容对齐 的本地化字符串。
        /// </summary>
        public static string Btn_HorizontalAlign_Name {
            get {
                return ResourceManager.GetString("Btn_HorizontalAlign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容对齐更新 的本地化字符串。
        /// </summary>
        public static string Btn_HorizontalAlign_OprtName {
            get {
                return ResourceManager.GetString("Btn_HorizontalAlign_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标数据(Base64) 的本地化字符串。
        /// </summary>
        public static string Btn_IconBase64_Name {
            get {
                return ResourceManager.GetString("Btn_IconBase64_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标数据更新 的本地化字符串。
        /// </summary>
        public static string Btn_IconBase64_OprtName {
            get {
                return ResourceManager.GetString("Btn_IconBase64_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标位置 的本地化字符串。
        /// </summary>
        public static string Btn_IconPlacement_Name {
            get {
                return ResourceManager.GetString("Btn_IconPlacement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标位置更新 的本地化字符串。
        /// </summary>
        public static string Btn_IconPlacement_OprtName {
            get {
                return ResourceManager.GetString("Btn_IconPlacement_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标尺寸 的本地化字符串。
        /// </summary>
        public static string Btn_IconSize_Name {
            get {
                return ResourceManager.GetString("Btn_IconSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标尺寸更新 的本地化字符串。
        /// </summary>
        public static string Btn_IconSize_OprtName {
            get {
                return ResourceManager.GetString("Btn_IconSize_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图文间距 的本地化字符串。
        /// </summary>
        public static string Btn_IconSpacing_Name {
            get {
                return ResourceManager.GetString("Btn_IconSpacing_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图文间距更新 的本地化字符串。
        /// </summary>
        public static string Btn_IconSpacing_OprtName {
            get {
                return ResourceManager.GetString("Btn_IconSpacing_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        public static string Btn_IsBold_Name {
            get {
                return ResourceManager.GetString("Btn_IsBold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗更新 的本地化字符串。
        /// </summary>
        public static string Btn_IsBold_OprtName {
            get {
                return ResourceManager.GetString("Btn_IsBold_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        public static string Btn_IsEnabled_Name {
            get {
                return ResourceManager.GetString("Btn_IsEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态更新 的本地化字符串。
        /// </summary>
        public static string Btn_IsEnabled_OprtName {
            get {
                return ResourceManager.GetString("Btn_IsEnabled_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        public static string Btn_IsItalic_Name {
            get {
                return ResourceManager.GetString("Btn_IsItalic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体更新 的本地化字符串。
        /// </summary>
        public static string Btn_IsItalic_OprtName {
            get {
                return ResourceManager.GetString("Btn_IsItalic_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        public static string Btn_IsUnderline_Name {
            get {
                return ResourceManager.GetString("Btn_IsUnderline_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线更新 的本地化字符串。
        /// </summary>
        public static string Btn_IsUnderline_OprtName {
            get {
                return ResourceManager.GetString("Btn_IsUnderline_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮布局位置原子 的本地化字符串。
        /// </summary>
        public static string Btn_LayoutGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Btn_LayoutGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外边距 的本地化字符串。
        /// </summary>
        public static string Btn_Margin_Name {
            get {
                return ResourceManager.GetString("Btn_Margin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外边距更新 的本地化字符串。
        /// </summary>
        public static string Btn_Margin_OprtName {
            get {
                return ResourceManager.GetString("Btn_Margin_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        public static string Btn_Opacity_Name {
            get {
                return ResourceManager.GetString("Btn_Opacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度更新 的本地化字符串。
        /// </summary>
        public static string Btn_Opacity_OprtName {
            get {
                return ResourceManager.GetString("Btn_Opacity_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内边距 的本地化字符串。
        /// </summary>
        public static string Btn_Padding_Name {
            get {
                return ResourceManager.GetString("Btn_Padding_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内边距更新 的本地化字符串。
        /// </summary>
        public static string Btn_Padding_OprtName {
            get {
                return ResourceManager.GetString("Btn_Padding_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示图标 的本地化字符串。
        /// </summary>
        public static string Btn_ShowIcon_Name {
            get {
                return ResourceManager.GetString("Btn_ShowIcon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示图标更新 的本地化字符串。
        /// </summary>
        public static string Btn_ShowIcon_OprtName {
            get {
                return ResourceManager.GetString("Btn_ShowIcon_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示文本 的本地化字符串。
        /// </summary>
        public static string Btn_ShowText_Name {
            get {
                return ResourceManager.GetString("Btn_ShowText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示文本更新 的本地化字符串。
        /// </summary>
        public static string Btn_ShowText_OprtName {
            get {
                return ResourceManager.GetString("Btn_ShowText_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮样式外观原子 的本地化字符串。
        /// </summary>
        public static string Btn_StyleGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Btn_StyleGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文案 的本地化字符串。
        /// </summary>
        public static string Btn_ToolTip_Name {
            get {
                return ResourceManager.GetString("Btn_ToolTip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文案更新 的本地化字符串。
        /// </summary>
        public static string Btn_ToolTip_OprtName {
            get {
                return ResourceManager.GetString("Btn_ToolTip_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标按钮gkg 的本地化字符串。
        /// </summary>
        public static string IconButton {
            get {
                return ResourceManager.GetString("IconButton", resourceCulture);
            }
        }
    }
}
