//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.MapCell.Generic.Control.Lable {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Lable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Lable() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.MapCell.Generic.Control.MapCell_Lable_New.Resource_Lable", typeof(Resource_Lable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 标签gkg 的本地化字符串。
        /// </summary>
        internal static string Lable {
            get {
                return ResourceManager.GetString("Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色 的本地化字符串。
        /// </summary>
        internal static string Lable_BackgroundColor_Name {
            get {
                return ResourceManager.GetString("Lable_BackgroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景色更新 的本地化字符串。
        /// </summary>
        internal static string Lable_BackgroundColor_OprtName {
            get {
                return ResourceManager.GetString("Lable_BackgroundColor_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框颜色 的本地化字符串。
        /// </summary>
        internal static string Lable_BorderBrush_Name {
            get {
                return ResourceManager.GetString("Lable_BorderBrush_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框颜色更新 的本地化字符串。
        /// </summary>
        internal static string Lable_BorderBrush_OprtName {
            get {
                return ResourceManager.GetString("Lable_BorderBrush_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框厚度 的本地化字符串。
        /// </summary>
        internal static string Lable_BorderThickness_Name {
            get {
                return ResourceManager.GetString("Lable_BorderThickness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框厚度更新 的本地化字符串。
        /// </summary>
        internal static string Lable_BorderThickness_OprtName {
            get {
                return ResourceManager.GetString("Lable_BorderThickness_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标样式 的本地化字符串。
        /// </summary>
        internal static string Lable_CursorType_Name {
            get {
                return ResourceManager.GetString("Lable_CursorType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标样式更新 的本地化字符串。
        /// </summary>
        internal static string Lable_CursorType_OprtName {
            get {
                return ResourceManager.GetString("Lable_CursorType_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签数据设置原子 的本地化字符串。
        /// </summary>
        internal static string Lable_DataGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Lable_DataGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体族 的本地化字符串。
        /// </summary>
        internal static string Lable_FontFamily_Name {
            get {
                return ResourceManager.GetString("Lable_FontFamily_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体族更新 的本地化字符串。
        /// </summary>
        internal static string Lable_FontFamily_OprtName {
            get {
                return ResourceManager.GetString("Lable_FontFamily_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签字体排版原子 的本地化字符串。
        /// </summary>
        internal static string Lable_FontGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Lable_FontGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        internal static string Lable_FontSize_Name {
            get {
                return ResourceManager.GetString("Lable_FontSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号更新 的本地化字符串。
        /// </summary>
        internal static string Lable_FontSize_OprtName {
            get {
                return ResourceManager.GetString("Lable_FontSize_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字颜色 的本地化字符串。
        /// </summary>
        internal static string Lable_ForegroundColor_Name {
            get {
                return ResourceManager.GetString("Lable_ForegroundColor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文字颜色更新 的本地化字符串。
        /// </summary>
        internal static string Lable_ForegroundColor_OprtName {
            get {
                return ResourceManager.GetString("Lable_ForegroundColor_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平对齐 的本地化字符串。
        /// </summary>
        internal static string Lable_HorizontalAlign_Name {
            get {
                return ResourceManager.GetString("Lable_HorizontalAlign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水平对齐更新 的本地化字符串。
        /// </summary>
        internal static string Lable_HorizontalAlign_OprtName {
            get {
                return ResourceManager.GetString("Lable_HorizontalAlign_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗 的本地化字符串。
        /// </summary>
        internal static string Lable_IsBold_Name {
            get {
                return ResourceManager.GetString("Lable_IsBold_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粗更新 的本地化字符串。
        /// </summary>
        internal static string Lable_IsBold_OprtName {
            get {
                return ResourceManager.GetString("Lable_IsBold_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string Lable_IsEnabled_Name {
            get {
                return ResourceManager.GetString("Lable_IsEnabled_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态更新 的本地化字符串。
        /// </summary>
        internal static string Lable_IsEnabled_OprtName {
            get {
                return ResourceManager.GetString("Lable_IsEnabled_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        internal static string Lable_IsItalic_Name {
            get {
                return ResourceManager.GetString("Lable_IsItalic_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体更新 的本地化字符串。
        /// </summary>
        internal static string Lable_IsItalic_OprtName {
            get {
                return ResourceManager.GetString("Lable_IsItalic_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        internal static string Lable_IsUnderline_Name {
            get {
                return ResourceManager.GetString("Lable_IsUnderline_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线更新 的本地化字符串。
        /// </summary>
        internal static string Lable_IsUnderline_OprtName {
            get {
                return ResourceManager.GetString("Lable_IsUnderline_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签文本 的本地化字符串。
        /// </summary>
        internal static string Lable_LableText_Name {
            get {
                return ResourceManager.GetString("Lable_LableText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签文本更新 的本地化字符串。
        /// </summary>
        internal static string Lable_LableText_OprtName {
            get {
                return ResourceManager.GetString("Lable_LableText_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签布局位置原子 的本地化字符串。
        /// </summary>
        internal static string Lable_LayoutGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Lable_LayoutGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行高倍数 的本地化字符串。
        /// </summary>
        internal static string Lable_LineHeight_Name {
            get {
                return ResourceManager.GetString("Lable_LineHeight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行高倍数更新 的本地化字符串。
        /// </summary>
        internal static string Lable_LineHeight_OprtName {
            get {
                return ResourceManager.GetString("Lable_LineHeight_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外边距 的本地化字符串。
        /// </summary>
        internal static string Lable_Margin_Name {
            get {
                return ResourceManager.GetString("Lable_Margin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外边距更新 的本地化字符串。
        /// </summary>
        internal static string Lable_Margin_OprtName {
            get {
                return ResourceManager.GetString("Lable_Margin_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度 的本地化字符串。
        /// </summary>
        internal static string Lable_Opacity_Name {
            get {
                return ResourceManager.GetString("Lable_Opacity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 透明度更新 的本地化字符串。
        /// </summary>
        internal static string Lable_Opacity_OprtName {
            get {
                return ResourceManager.GetString("Lable_Opacity_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内边距 的本地化字符串。
        /// </summary>
        internal static string Lable_Padding_Name {
            get {
                return ResourceManager.GetString("Lable_Padding_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内边距更新 的本地化字符串。
        /// </summary>
        internal static string Lable_Padding_OprtName {
            get {
                return ResourceManager.GetString("Lable_Padding_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签样式外观原子 的本地化字符串。
        /// </summary>
        internal static string Lable_StyleGroup_OprtCellName {
            get {
                return ResourceManager.GetString("Lable_StyleGroup_OprtCellName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本对齐 的本地化字符串。
        /// </summary>
        internal static string Lable_TextAlignment_Name {
            get {
                return ResourceManager.GetString("Lable_TextAlignment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本对齐更新 的本地化字符串。
        /// </summary>
        internal static string Lable_TextAlignment_OprtName {
            get {
                return ResourceManager.GetString("Lable_TextAlignment_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文案 的本地化字符串。
        /// </summary>
        internal static string Lable_ToolTip_Name {
            get {
                return ResourceManager.GetString("Lable_ToolTip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示文案更新 的本地化字符串。
        /// </summary>
        internal static string Lable_ToolTip_OprtName {
            get {
                return ResourceManager.GetString("Lable_ToolTip_OprtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直对齐 的本地化字符串。
        /// </summary>
        internal static string Lable_VerticalAlign_Name {
            get {
                return ResourceManager.GetString("Lable_VerticalAlign_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垂直对齐更新 的本地化字符串。
        /// </summary>
        internal static string Lable_VerticalAlign_OprtName {
            get {
                return ResourceManager.GetString("Lable_VerticalAlign_OprtName", resourceCulture);
            }
        }
    }
}
