//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GKG.Map.UIDataObj.AuxiliaryInfo {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GKG.Map.UIDataObj.AuxiliaryInfo.ResourceNames", typeof(ResourceNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对使用此强类型资源类的所有资源查找执行重写
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 辅助信息 的本地化字符串
        /// </summary>
        internal static string AuxiliaryInfo {
            get {
                return ResourceManager.GetString("AuxiliaryInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存参数 的本地化字符串
        /// </summary>
        internal static string SaveParams {
            get {
                return ResourceManager.GetString("SaveParams", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 校验程序 的本地化字符串
        /// </summary>
        internal static string VerifyProgram {
            get {
                return ResourceManager.GetString("VerifyProgram", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上线 的本地化字符串
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下线 的本地化字符串
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 程序名称 的本地化字符串
        /// </summary>
        internal static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 工单号 的本地化字符串
        /// </summary>
        internal static string WorkOrderNo {
            get {
                return ResourceManager.GetString("WorkOrderNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶水信息 的本地化字符串
        /// </summary>
        internal static string RightValveGlueInfo {
            get {
                return ResourceManager.GetString("RightValveGlueInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶水包装ID 的本地化字符串
        /// </summary>
        internal static string RightValveGluePackageId {
            get {
                return ResourceManager.GetString("RightValveGluePackageId", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶水生产批次号 的本地化字符串
        /// </summary>
        internal static string RightValveGlueBatchNo {
            get {
                return ResourceManager.GetString("RightValveGlueBatchNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶水制造料号 的本地化字符串
        /// </summary>
        internal static string RightValveGlueMaterialNo {
            get {
                return ResourceManager.GetString("RightValveGlueMaterialNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右阀胶水生产日期 的本地化字符串
        /// </summary>
        internal static string RightValveGlueProdDate {
            get {
                return ResourceManager.GetString("RightValveGlueProdDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 双阀模式 的本地化字符串
        /// </summary>
        internal static string IsDualValve {
            get {
                return ResourceManager.GetString("IsDualValve", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水信息 的本地化字符串
        /// </summary>
        internal static string LeftValveGlueInfo {
            get {
                return ResourceManager.GetString("LeftValveGlueInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水包装ID 的本地化字符串
        /// </summary>
        internal static string LeftValveGluePackageId {
            get {
                return ResourceManager.GetString("LeftValveGluePackageId", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水生产批次号 的本地化字符串
        /// </summary>
        internal static string LeftValveGlueBatchNo {
            get {
                return ResourceManager.GetString("LeftValveGlueBatchNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水制造料号 的本地化字符串
        /// </summary>
        internal static string LeftValveGlueMaterialNo {
            get {
                return ResourceManager.GetString("LeftValveGlueMaterialNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左阀胶水生产日期 的本地化字符串
        /// </summary>
        internal static string LeftValveGlueProdDate {
            get {
                return ResourceManager.GetString("LeftValveGlueProdDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设备ID 的本地化字符串
        /// </summary>
        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设备名称 的本地化字符串
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Mac地址 的本地化字符串
        /// </summary>
        internal static string MacAddress {
            get {
                return ResourceManager.GetString("MacAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 IP地址 的本地化字符串
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 产品信息 的本地化字符串
        /// </summary>
        internal static string ProductInfo {
            get {
                return ResourceManager.GetString("ProductInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 胶水名称 的本地化字符串
        /// </summary>
        internal static string GlueName {
            get {
                return ResourceManager.GetString("GlueName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 压电阀序号 的本地化字符串
        /// </summary>
        internal static string PiezoValveSerialNo {
            get {
                return ResourceManager.GetString("PiezoValveSerialNo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 阀ID 的本地化字符串
        /// </summary>
        internal static string ValveId {
            get {
                return ResourceManager.GetString("ValveId", resourceCulture);
            }
        }
    }
}
